Feature/bl UI 3279 mobile view tabs
etn-ccis/blui-react-component-library pull request #805
Opened 2023-09-21 16:32 UTC by andrupu

Fixes # BLUI-3279

#### Changes proposed in this Pull Request:

-Update dev docs styling to match the designs for mobile view on smaller screens.

-Main point of address will be updates to the Playground screen.

-This will NOT include multilayer drawer updates.

#### To Test: 

- yarn start:reactdev

2023-09-22 11:31 UTC, surajeaton reviewed
@andrupu  Prettier and lint are failing.
Please run yarn precommit.

2023-09-22 12:13 UTC, ektaghag-eaton commented
@andrupu , can you add figma link ?

2023-09-22 12:56 UTC, daileytj commented
> @andrupu , can you add figma link ?

https://www.figma.com/file/Nydz8n8HBj6U3ZtULja3gD/%F0%9F%92%AB-Brightlayer-UI-Tokens-%2B-Components-(in-Material-Design-3)?type=design&node-id=410%3A825&mode=design&t=gUHmaUsG82YTNfoB-1

2023-09-27 12:36 UTC, huayunh requested changes
- Please resolve your lint error about "Missing return type on function"
- Please run prettier
- Please add the black overlay thing (scrim) we mentioned. Ideally, onclick the black overlay should dismay the expanded bottom sheet
- Please add the animation to expand / collapse the drawer
- Please remove all the unused code that you commented out
- Something is causing an undesired overflow. For example, this should not be scrolling up and down like this:
https://github.com/etn-ccis/blui-react-component-library/assets/8997218/acf7693e-61b9-443e-a0e1-0610b37a4dae

2023-09-27 12:36 UTC, huayunh commented on docs/src/shared/PreviewComponentWithCode.tsx
>                       * We take the height of the appbar/tabs out of the 70vh portion
Remember to update the inline comment

2023-09-27 12:36 UTC, huayunh commented on docs/src/shared/PlaygroundDrawer.tsx
> +    type PlaygroundTabPanelProps = {
we usually take the type declaration out of the component scope.

2023-09-27 12:36 UTC, huayunh commented on docs/src/shared/PlaygroundDrawer.tsx
> +    type PlaygroundTabPanelProps = {
In  fact, both `PlaygroundTabPanelProps` and `PlaygroundTabPanel` can probably be taken out of `PlaygroundDrawer` to make `PlaygroundDrawer` code shorter and easier to read

2023-09-27 12:36 UTC, huayunh commented on docs/src/shared/PlaygroundDrawer.tsx
> +                        visibility: 'visible !important',
You should not be turning the drawer on/off via these CSS attributes

2023-10-12 11:41 UTC, joebochill commented
Closing due to inactivity. It's going to be a while before this refactoring work is ready to go into dev...I would suggest setting up a new feature branch to use as the target for the incremental work until it is ready to be merged into dev.

2023-10-12 11:41 UTC, closed without merging